# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(email:'now2016@naver.com', password: 'sgbiznow+')

Product.create(category: '우산', total_amount: 50, lended_amount: 10)
Product.create(category: '재무계산기', total_amount: 5, lended_amount: 2)
Member.create(category: '경짱단', name: "김대한")
Member.create(category: '경짱단', name: "이혜인")
Member.create(category: '복지', name: "이찬하")
Member.create(category: '복지', name: "김창연")
Member.create(category: '복지', name: "문유림")
Member.create(category: '복지', name: "문지민")
Member.create(category: '복지', name: "김민규")
Member.create(category: '문체', name: "곽윤진")
Member.create(category: '문체', name: "이주찬")
Member.create(category: '문체', name: "김지훈")
Member.create(category: '문체', name: "백지민")
Member.create(category: '문체', name: "이채린")
Member.create(category: '사무', name: "김용관")
Member.create(category: '사무', name: "이가현")
Member.create(category: '사무', name: "정재용")
Member.create(category: '사무', name: "정채은")
Member.create(category: '사무', name: "최강민")
Member.create(category: '홍소', name: "조윤정")
Member.create(category: '홍소', name: "이인성")
Member.create(category: '홍소', name: "강민성")
Member.create(category: '홍소', name: "박주현")
Member.create(category: '홍소', name: "안혜원")
Member.create(category: 'A섹션', name: "김보아")
Member.create(category: 'A섹션', name: "김재호")
Member.create(category: 'A섹션', name: "김민규")
Member.create(category: 'A섹션', name: "구본휘")
Member.create(category: 'B섹션', name: "박준형")
Member.create(category: 'B섹션', name: "박수진")
Member.create(category: 'B섹션', name: "김한솔")
Member.create(category: 'B섹션', name: "김지윤")
Member.create(category: 'C섹션', name: "박하은")
Member.create(category: 'C섹션', name: "이경수")
Member.create(category: 'C섹션', name: "안헤원")
Member.create(category: 'C섹션', name: "왕애령")
Member.create(category: 'D섹션', name: "이승현")
Member.create(category: 'D섹션', name: "임지웅")
Member.create(category: 'D섹션', name: "이정우")
Member.create(category: 'D섹션', name: "장서현")
Member.create(category: 'E섹션', name: "한수민")
Member.create(category: 'E섹션', name: "황문준")
Member.create(category: 'E섹션', name: "정현준")
Member.create(category: 'E섹션', name: "한송이")