# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(email:'now2016@naver.com', password: 'sgbiznow+')

Product.create(category: '우산', total_amount: 50, lended_amount: 10)
Product.create(category: '재무계산기', total_amount: 5, lended_amount: 2)

Members.create(category: '복지', name: "이찬하")
Members.create(category: '복지', name: "김창연")
Members.create(category: '복지', name: "문유림")
Members.create(category: '복지', name: "문지민")
Members.create(category: '복지', name: "김창연")
Members.create(category: '문체', name: "곽윤진")
Members.create(category: '문체', name: "이주찬")
Members.create(category: '문체', name: "김지훈")
Members.create(category: '문체', name: "백지민")
Members.create(category: '문체', name: "이채린")
Members.create(category: '사무', name: "김용관")
Members.create(category: '사무', name: "이가현")
Members.create(category: '사무', name: "정재용")
Members.create(category: '사무', name: "정채은")
Members.create(category: '사무', name: "최강민")
Members.create(category: '홍소', name: "조윤정")
Members.create(category: '홍소', name: "이인성")
Members.create(category: '홍소', name: "강민성")
Members.create(category: '홍소', name: "박주현")
Members.create(category: '홍소', name: "안혜원")
Members.create(category: 'A섹션', name: "김보아")
Members.create(category: 'A섹션', name: "김재호")
Members.create(category: 'A섹션', name: "권순우")
Members.create(category: 'A섹션', name: "김나연")
Members.create(category: 'B섹션', name: "박준형")
Members.create(category: 'B섹션', name: "박수진")
Members.create(category: 'B섹션', name: "김예지")
Members.create(category: 'B섹션', name: "김태원")
Members.create(category: 'C섹션', name: "박하은")
Members.create(category: 'C섹션', name: "이경수")
Members.create(category: 'C섹션', name: "유재호")
Members.create(category: 'C섹션', name: "서지윤")
Members.create(category: 'D섹션', name: "이승현")
Members.create(category: 'D섹션', name: "임지웅")
Members.create(category: 'D섹션', name: "이동호")
Members.create(category: 'D섹션', name: "장재혁")
Members.create(category: 'E섹션', name: "한수민")
Members.create(category: 'E섹션', name: "황문준")
Members.create(category: 'E섹션', name: "조준형")
Members.create(category: 'E섹션', name: "조민주")